### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by kesla** [ellell/github-rsvp#4]
Tried installing, getting this after logging in:

```
err { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
  code: 404 }
```

@ellell does this work for you? E.g. is this just a problem on my end?

**Comment by ellell** [comment]
@kesla Yeah, I'm getting a similar issue. Thanks for flagging, I'll look into that! 

It seems to be working when I use this command though `github-rsvp -t <access-token>`, does that work for you?

**Comment by kesla** [comment]
I'll take a look later, I'd need to setup my own access token right?

**Comment by kesla** [comment]
@ellell ^^^

**Comment by ellell** [comment]
@kesla yeah, exactly.
